require('dotenv').config();
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var mongoose = require("mongoose")
var session = require('express-session');

var docterRouter = require('./routes/doctors');
var usersRouter = require('./routes/users');
var hospitalRouter = require('./routes/hospital')
var prescriptionRouter = require('./routes/prescription')


var app = express();
const port = 4000

//mongo db connection with better options
// IMPORTANT: Replace YOUR_PASSWORD_HERE with your actual MongoDB password!
// Your password was either the autogenerated one (NeDyXoFh) or the one you created
const mongoURI = process.env.MONGODB_URI || "mongodb+srv://<username:password>@hft.h7axldb.mongodb.net/medeasedb?retryWrites=true&w=majority&appName=HFT";

// MongoDB connection event listeners
mongoose.connection.on('connecting', () => {
  console.log('🔄 Connecting to MongoDB...')
})

mongoose.connection.on('connected', () => {
  console.log('✓ Connected to MongoDB database')
  console.log('✓ Database name:', mongoose.connection.db.databaseName)
})

mongoose.connection.on('error', (err) => {
  console.error('✗ MongoDB connection error:', err.message)
  if (err.message.includes("authentication failed") || err.message.includes("bad auth")) {
    console.error('⚠ AUTHENTICATION ERROR: Password is incorrect!')
    console.error('   Please check your password in app.js line 21')
    console.error('   Steps to fix:')
    console.error('   1. Go to MongoDB Atlas → Database Access')
    console.error('   2. Find user "achus2710_db_user"')
    console.error('   3. Click "Edit" → "Edit Password"')
    console.error('   4. Set a new password and update app.js line 21')
  }
})

mongoose.connection.on('disconnected', () => {
  console.log('⚠ MongoDB disconnected')
})

// Attempt to connect
mongoose.connect(mongoURI, {
  serverSelectionTimeoutMS: 10000, // Increased timeout to 10s
  socketTimeoutMS: 45000, // Close sockets after 45s of inactivity
}).catch((err) => {
  console.error("✗ Could not connect to MongoDB")
  console.error("Error details:", err.message)
  console.error("If using MongoDB Atlas, verify:")
  console.error("  1. Your cluster is running (not paused)")
  console.error("  2. Your IP address is whitelisted in Network Access")
  console.error("  3. Your username and password are correct")
})


// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

// Session configuration - MUST be before routes
app.use(session({
  secret: 'medease-secret-key-2024', // Change this to a secure random string in production
  resave: false,
  saveUninitialized: false,
  cookie: {
    maxAge: 24 * 60 * 60 * 1000, // 24 hours
    httpOnly: true,
    secure: false // Set to true if using HTTPS
  }
}));




app.use('/doctor', docterRouter);
app.use('/prescription', prescriptionRouter)
app.use("/hospital", hospitalRouter)
app.use('/', usersRouter);

// catch 404 and forward to error handler
app.use(function (req, res, next) {
  next(createError(404));
});

// error handler
app.use(function (err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  console.log(err);
  res.render('user/error');
});

// Start server - will work even if MongoDB connection fails
let serverStarted = false;

function startServer() {
  if (!serverStarted) {
    serverStarted = true;
    app.listen(port, () => {
      if (mongoose.connection.readyState === 1) {
        console.log(`✓ Server listening on http://localhost:${port} (MongoDB connected)`);
      } else {
        console.log(`⚠ Server listening on http://localhost:${port} (MongoDB not connected)`);
        console.log(`⚠ Database operations will fail until MongoDB connection is established`);
      }
    });
  }
}

// Wait for MongoDB connection before starting server
mongoose.connection.once('open', () => {
  console.log('✓ MongoDB connection is open and ready')
  startServer();
})

// Start server after a timeout if connection is taking too long
setTimeout(() => {
  startServer();
}, 3000) // Wait 3 seconds max for connection

module.exports = app;
